### ISSUE TITLE
Problemas com a fonte

### ISSUE THREAD

**Issue by HeliProGamer** [teiarruma/undertale-yellow-ptbr#12]
Parece que a fonte está tendo alguns problemas em tela cheia fora das batalhas, elas ficam meio bugadas quando o jogo é colocado em tela cheia, como se o texto estivesse duplicado. Aqui estão algumas fotos do acontecido:
![image](https://github.com/teiarruma/undertale-yellow-ptbr/assets/92348755/8e86f0ed-2e35-4907-95b4-fc9ccff89a21)
![image](https://github.com/teiarruma/undertale-yellow-ptbr/assets/92348755/67833e45-7b47-4e0f-8bfa-ab09a0f6edbe)

**Comment by marcel099** [comment]
Olá!

Embora eu agradeça por enviar o problema, preciso informar que ele é bem conhecido por nós e foi explicado no Discord, que é o local que organizamos para receber relato de problemas. Enviar lá é a orientação que nós fornecemos no documento descritor aqui neste repositório; está na seção "Entrar no nosso Discord" como "Quer reportar erros?".

Repito o que foi falado no **servidor**, local que é a **nossa central de informações detalhadas**:

> Estamos cientes de um problema de rabiscos aparecendo ao redor de umas letras de algumas das fontes. Isso aconteceu no computador de dois de nossos contribuidores da tradução de Undertale Yellow, embora o problema não aconteça no computador dos outros.
> Como solução, bastou a eles dois não deixarem o jogo em tela cheia. Outra solução foi mudar o perfil de configurações do monitor, mas essa solução somente um dos dois conseguiu aplicar. 

Outra forma de tentar solucionar o problema é mudar a resolução do monitor. Isso também foi explicado em detalhes no server.

Vou aproveitar a oportunidade para desativar a aba _Issues_ no repositório, pois, inclusive, um dos principais objetivos do nosso servidor no Discord é servir como local para receber relatos de problemas.
